from __future__ import absolute_import
"""
Data models for OB CASH 3.0.

Defines typed structures for market data, signals, and configuration.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any, List


@dataclass
class Candle:
    """Single candlestick data."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    def to_dict(self) -> Dict[str, float]:
        """Convert to dictionary."""
        return {
            "Open": self.open,
            "High": self.high,
            "Low": self.low,
            "Close": self.close,
            "Volume": self.volume,
        }


@dataclass
class Signal:
    """Trading signal generated by the engine."""
    asset: str
    interval: str
    timestamp: datetime
    action: str  # COMPRA, VENDA, EVITA, AGUARDAR
    strength: str  # FORTE, MODERADO, FRACO, NEUTRO
    score: float
    price: float
    sl: Optional[float] = None
    tp: Optional[float] = None
    atr: float = 0.0
    rsi: float = 50.0
    adx: float = 20.0
    macd_hist: float = 0.0
    stoch: float = 50.0
    bb_width: float = 0.0
    market_regime: str = "NORMAL"
    session: str = ""
    session_raw: str = ""
    mtf_confirmation: str = "N/A"
    divergence: str = "NONE"
    source: str = ""
    confidence_score: float = 0.0
    confidence_label: str = "OBSERVAR"
    policy_state: str = "neutral"
    policy_notes: List[str] = field(default_factory=list)
    technical_score: float = 0.0
    ml_score: float = 0.0
    ml_confidence: float = 0.0
    ml_backend: str = "none"
    ml_used: bool = False
    decision_score: float = 0.0
    selection_reason: str = ""
    note: str = ""
    conditions_buy: List[bool] = field(default_factory=list)
    conditions_sell: List[bool] = field(default_factory=list)
    filters: List[str] = field(default_factory=list)
    raw_data: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage/transmission."""
        return {
            "asset": self.asset,
            "interval": self.interval,
            "timestamp": self.timestamp.isoformat(),
            "action": self.action,
            "strength": self.strength,
            "score": self.score,
            "price": f"{self.price:.5f}",
            "sl": f"{self.sl:.5f}" if self.sl else "---",
            "tp": f"{self.tp:.5f}" if self.tp else "---",
            "atr": f"{self.atr:.5f}",
            "rsi": f"{self.rsi:.1f}",
            "adx": f"{self.adx:.1f}",
            "macd_hist": f"{self.macd_hist:+.6f}",
            "stoch": f"{self.stoch:.1f}",
            "bb_width": f"{self.bb_width * 100:.4f}%",
            "mercado": self.market_regime,
            "session": self.session,
            "mtf": self.mtf_confirmation,
            "diverg": self.divergence,
            "fonte": self.source,
            "confidence_score": f"{self.confidence_score:.1f}",
            "confidence_label": self.confidence_label,
            "policy_state": self.policy_state,
            "time": self.timestamp.strftime("%H:%M:%S"),
            "candles": len(self.raw_data) if self.raw_data else 0,
        }

    @property
    def is_entry_signal(self) -> bool:
        """Check if this is a tradable entry signal."""
        return self.action in ("COMPRA", "VENDA") and self.strength == "FORTE"


@dataclass
class BacktestResult:
    """Results from a backtest run."""
    total_trades: int
    wins: int
    losses: int
    draw_trades: int
    win_rate: float  # 0.0 to 1.0
    profit_factor: float
    total_pnl_pct: float
    max_drawdown_pct: float
    avg_score: float
    trades: List[Dict[str, Any]]
    equity_curve: List[float]

    @property
    def profit_factor_str(self) -> str:
        """Formatted profit factor."""
        return f"{self.profit_factor:.2f}"

    @property
    def win_rate_str(self) -> str:
        """Formatted win rate percentage."""
        return f"{self.win_rate * 100:.1f}%"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "trades": self.total_trades,
            "wins": self.wins,
            "losses": self.losses,
            "draw": self.draw_trades,
            "win_rate": self.win_rate_str,
            "profit_factor": self.profit_factor_str,
            "total_pnl": f"{self.total_pnl_pct:+.3f}%",
            "max_drawdown": f"{self.max_drawdown_pct:.3f}%",
            "avg_score": f"{self.avg_score:.1f}%",
        }
